// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYjeFT1F7zFJvnzGPmYNGkS7fX3tAjzTI',
    appId: '1:961973999462:web:771b4605e776ec99821aa7',
    messagingSenderId: '961973999462',
    projectId: 'trials-project-fluxpert',
    authDomain: 'trials-project-fluxpert.firebaseapp.com',
    storageBucket: 'trials-project-fluxpert.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOJHdOkr_iXNHicp29VNjb4OrxQ9xLJYE',
    appId: '1:961973999462:android:edb98f0bedb5ec3f821aa7',
    messagingSenderId: '961973999462',
    projectId: 'trials-project-fluxpert',
    storageBucket: 'trials-project-fluxpert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdtWsbILMmQjFxPT3XHvIRznatxgGeWLw',
    appId: '1:961973999462:ios:c62574d036a8d710821aa7',
    messagingSenderId: '961973999462',
    projectId: 'trials-project-fluxpert',
    storageBucket: 'trials-project-fluxpert.appspot.com',
    iosClientId: '961973999462-08ru2v87633l6cboa1u7ors3975q6nrq.apps.googleusercontent.com',
    iosBundleId: 'com.fluxpert.trialsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdtWsbILMmQjFxPT3XHvIRznatxgGeWLw',
    appId: '1:961973999462:ios:c62574d036a8d710821aa7',
    messagingSenderId: '961973999462',
    projectId: 'trials-project-fluxpert',
    storageBucket: 'trials-project-fluxpert.appspot.com',
    iosClientId: '961973999462-08ru2v87633l6cboa1u7ors3975q6nrq.apps.googleusercontent.com',
    iosBundleId: 'com.fluxpert.trialsProject',
  );
}
